//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagingToolkit.Service.Web.CommandService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twit88.com/messagingtoolkit/v1.0", ConfigurationName="CommandService.IServiceProviderContract")]
    public interface IServiceProviderContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twit88.com/messagingtoolkit/v1.0/IServiceProviderContract/Execute", ReplyAction="http://www.twit88.com/messagingtoolkit/v1.0/IServiceProviderContract/ExecuteRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MessagingToolkit.Service.Common.ServiceFault), Action="http://www.twit88.com/messagingtoolkit/v1.0/IServiceProviderContract/ExecuteServi" +
            "ceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MessagingToolkit.Service.Common")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.AddGatewayCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GetGatewayStatusCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.StartGatewayCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.StopGatewayCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.AddIncomingMessageCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.DeleteIncomingMessageCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GetAllIncomingMessagesCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GetIncomingMessageByIdCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.UpdateIncomingMessageCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.AddOutgoingMessageCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.DeleteGatewayCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.DeleteOutgoingMessageCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GetAllGatewaysCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GetAllOutgoingMessagesCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GetAppConfigCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GetGatewayByIdCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GetOutgoingMessageByIdCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.UpdateGatewayCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GetOutgoingMessagesByStatusCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GetUnsentMessagesCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.UpdateOutgoingMessageCommand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Provider.Commands.GatewayStatusInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Common.Models.Gateway))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Common.Models.Incoming))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Common.Models.Outgoing))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Common.Models.Incoming[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Common.Models.Gateway[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Common.Models.Outgoing[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Common.Models.AppConfig))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MessagingToolkit.Service.Common.ServiceFault))]
        object Execute(object command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twit88.com/messagingtoolkit/v1.0/IServiceProviderContract/Execute", ReplyAction="http://www.twit88.com/messagingtoolkit/v1.0/IServiceProviderContract/ExecuteRespo" +
            "nse")]
        System.Threading.Tasks.Task<object> ExecuteAsync(object command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProviderContractChannel : MessagingToolkit.Service.Web.CommandService.IServiceProviderContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProviderContractClient : System.ServiceModel.ClientBase<MessagingToolkit.Service.Web.CommandService.IServiceProviderContract>, MessagingToolkit.Service.Web.CommandService.IServiceProviderContract {
        
        public ServiceProviderContractClient() {
        }
        
        public ServiceProviderContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProviderContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProviderContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProviderContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object Execute(object command) {
            return base.Channel.Execute(command);
        }
        
        public System.Threading.Tasks.Task<object> ExecuteAsync(object command) {
            return base.Channel.ExecuteAsync(command);
        }
    }
}
